<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6pkvtk7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6pkvtk7/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6pkvtk7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6pkvtk7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6pkvtk7\appProdProjectContainer([
    'container.build_hash' => '6pkvtk7',
    'container.build_id' => '26e447e5',
    'container.build_time' => 1556049581,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6pkvtk7');
